// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt192 = 192

type IDt192 struct {
	refid.ID
}

func (r *IDt192) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt192) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt192) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt192) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt192) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt192) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt192) toID() refid.ID {
	return r.ID
}

func (r IDt192) tagVal() byte {
	return tagIDt192
}

type NullIDt192 struct {
	refid.NullID
}

func (u *NullIDt192) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt192) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt192) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt192) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
