// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt125 = 125

type IDt125 struct {
	refid.ID
}

func (r *IDt125) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt125) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt125) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt125) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt125) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt125) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt125) toID() refid.ID {
	return r.ID
}

func (r IDt125) tagVal() byte {
	return tagIDt125
}

type NullIDt125 struct {
	refid.NullID
}

func (u *NullIDt125) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt125) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt125) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt125) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
