// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt86 = 86

type IDt86 struct {
	refid.ID
}

func (r *IDt86) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt86) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt86) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt86) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt86) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt86) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt86) toID() refid.ID {
	return r.ID
}

func (r IDt86) tagVal() byte {
	return tagIDt86
}

type NullIDt86 struct {
	refid.NullID
}

func (u *NullIDt86) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt86) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt86) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt86) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
