// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt84 = 84

type IDt84 struct {
	refid.ID
}

func (r *IDt84) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt84) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt84) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt84) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt84) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt84) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt84) toID() refid.ID {
	return r.ID
}

func (r IDt84) tagVal() byte {
	return tagIDt84
}

type NullIDt84 struct {
	refid.NullID
}

func (u *NullIDt84) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt84) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt84) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt84) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
