// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt82 = 82

type IDt82 struct {
	refid.ID
}

func (r *IDt82) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt82) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt82) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt82) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt82) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt82) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt82) toID() refid.ID {
	return r.ID
}

func (r IDt82) tagVal() byte {
	return tagIDt82
}

type NullIDt82 struct {
	refid.NullID
}

func (u *NullIDt82) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt82) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt82) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt82) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
