// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt76 = 76

type IDt76 struct {
	refid.ID
}

func (r *IDt76) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt76) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt76) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt76) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt76) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt76) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt76) toID() refid.ID {
	return r.ID
}

func (r IDt76) tagVal() byte {
	return tagIDt76
}

type NullIDt76 struct {
	refid.NullID
}

func (u *NullIDt76) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt76) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt76) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt76) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
