// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt137 = 137

type IDt137 struct {
	refid.ID
}

func (r *IDt137) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt137) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt137) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt137) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt137) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt137) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt137) toID() refid.ID {
	return r.ID
}

func (r IDt137) tagVal() byte {
	return tagIDt137
}

type NullIDt137 struct {
	refid.NullID
}

func (u *NullIDt137) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt137) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt137) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt137) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
