// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt121 = 121

type IDt121 struct {
	refid.ID
}

func (r *IDt121) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt121) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt121) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt121) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt121) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt121) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt121) toID() refid.ID {
	return r.ID
}

func (r IDt121) tagVal() byte {
	return tagIDt121
}

type NullIDt121 struct {
	refid.NullID
}

func (u *NullIDt121) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt121) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt121) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt121) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
