// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt231 = 231

type IDt231 struct {
	refid.ID
}

func (r *IDt231) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt231) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt231) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt231) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt231) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt231) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt231) toID() refid.ID {
	return r.ID
}

func (r IDt231) tagVal() byte {
	return tagIDt231
}

type NullIDt231 struct {
	refid.NullID
}

func (u *NullIDt231) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt231) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt231) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt231) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
