// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt25 = 25

type IDt25 struct {
	refid.ID
}

func (r *IDt25) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt25) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt25) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt25) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt25) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt25) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt25) toID() refid.ID {
	return r.ID
}

func (r IDt25) tagVal() byte {
	return tagIDt25
}

type NullIDt25 struct {
	refid.NullID
}

func (u *NullIDt25) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt25) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt25) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt25) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
