// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt126 = 126

type IDt126 struct {
	refid.ID
}

func (r *IDt126) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt126) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt126) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt126) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt126) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt126) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt126) toID() refid.ID {
	return r.ID
}

func (r IDt126) tagVal() byte {
	return tagIDt126
}

type NullIDt126 struct {
	refid.NullID
}

func (u *NullIDt126) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt126) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt126) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt126) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
