// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt70 = 70

type IDt70 struct {
	refid.ID
}

func (r *IDt70) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt70) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt70) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt70) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt70) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt70) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt70) toID() refid.ID {
	return r.ID
}

func (r IDt70) tagVal() byte {
	return tagIDt70
}

type NullIDt70 struct {
	refid.NullID
}

func (u *NullIDt70) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt70) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt70) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt70) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
