// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt207 = 207

type IDt207 struct {
	refid.ID
}

func (r *IDt207) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt207) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt207) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt207) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt207) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt207) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt207) toID() refid.ID {
	return r.ID
}

func (r IDt207) tagVal() byte {
	return tagIDt207
}

type NullIDt207 struct {
	refid.NullID
}

func (u *NullIDt207) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt207) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt207) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt207) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
