// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt54 = 54

type IDt54 struct {
	refid.ID
}

func (r *IDt54) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt54) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt54) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt54) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt54) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt54) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt54) toID() refid.ID {
	return r.ID
}

func (r IDt54) tagVal() byte {
	return tagIDt54
}

type NullIDt54 struct {
	refid.NullID
}

func (u *NullIDt54) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt54) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt54) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt54) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
