// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt113 = 113

type IDt113 struct {
	refid.ID
}

func (r *IDt113) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt113) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt113) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt113) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt113) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt113) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt113) toID() refid.ID {
	return r.ID
}

func (r IDt113) tagVal() byte {
	return tagIDt113
}

type NullIDt113 struct {
	refid.NullID
}

func (u *NullIDt113) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt113) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt113) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt113) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
