// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt219 = 219

type IDt219 struct {
	refid.ID
}

func (r *IDt219) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt219) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt219) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt219) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt219) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt219) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt219) toID() refid.ID {
	return r.ID
}

func (r IDt219) tagVal() byte {
	return tagIDt219
}

type NullIDt219 struct {
	refid.NullID
}

func (u *NullIDt219) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt219) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt219) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt219) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
