// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt57 = 57

type IDt57 struct {
	refid.ID
}

func (r *IDt57) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt57) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt57) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt57) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt57) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt57) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt57) toID() refid.ID {
	return r.ID
}

func (r IDt57) tagVal() byte {
	return tagIDt57
}

type NullIDt57 struct {
	refid.NullID
}

func (u *NullIDt57) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt57) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt57) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt57) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
