// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt99 = 99

type IDt99 struct {
	refid.ID
}

func (r *IDt99) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt99) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt99) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt99) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt99) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt99) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt99) toID() refid.ID {
	return r.ID
}

func (r IDt99) tagVal() byte {
	return tagIDt99
}

type NullIDt99 struct {
	refid.NullID
}

func (u *NullIDt99) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt99) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt99) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt99) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
