// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt156 = 156

type IDt156 struct {
	refid.ID
}

func (r *IDt156) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt156) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt156) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt156) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt156) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt156) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt156) toID() refid.ID {
	return r.ID
}

func (r IDt156) tagVal() byte {
	return tagIDt156
}

type NullIDt156 struct {
	refid.NullID
}

func (u *NullIDt156) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt156) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt156) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt156) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
