// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt212 = 212

type IDt212 struct {
	refid.ID
}

func (r *IDt212) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt212) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt212) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt212) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt212) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt212) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt212) toID() refid.ID {
	return r.ID
}

func (r IDt212) tagVal() byte {
	return tagIDt212
}

type NullIDt212 struct {
	refid.NullID
}

func (u *NullIDt212) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt212) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt212) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt212) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
