// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt79 = 79

type IDt79 struct {
	refid.ID
}

func (r *IDt79) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt79) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt79) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt79) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt79) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt79) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt79) toID() refid.ID {
	return r.ID
}

func (r IDt79) tagVal() byte {
	return tagIDt79
}

type NullIDt79 struct {
	refid.NullID
}

func (u *NullIDt79) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt79) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt79) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt79) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
