// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt97 = 97

type IDt97 struct {
	refid.ID
}

func (r *IDt97) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt97) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt97) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt97) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt97) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt97) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt97) toID() refid.ID {
	return r.ID
}

func (r IDt97) tagVal() byte {
	return tagIDt97
}

type NullIDt97 struct {
	refid.NullID
}

func (u *NullIDt97) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt97) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt97) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt97) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
