// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt228 = 228

type IDt228 struct {
	refid.ID
}

func (r *IDt228) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt228) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt228) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt228) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt228) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt228) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt228) toID() refid.ID {
	return r.ID
}

func (r IDt228) tagVal() byte {
	return tagIDt228
}

type NullIDt228 struct {
	refid.NullID
}

func (u *NullIDt228) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt228) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt228) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt228) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
