// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt88 = 88

type IDt88 struct {
	refid.ID
}

func (r *IDt88) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt88) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt88) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt88) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt88) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt88) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt88) toID() refid.ID {
	return r.ID
}

func (r IDt88) tagVal() byte {
	return tagIDt88
}

type NullIDt88 struct {
	refid.NullID
}

func (u *NullIDt88) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt88) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt88) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt88) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
