// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt171 = 171

type IDt171 struct {
	refid.ID
}

func (r *IDt171) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt171) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt171) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt171) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt171) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt171) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt171) toID() refid.ID {
	return r.ID
}

func (r IDt171) tagVal() byte {
	return tagIDt171
}

type NullIDt171 struct {
	refid.NullID
}

func (u *NullIDt171) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt171) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt171) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt171) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
