// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt93 = 93

type IDt93 struct {
	refid.ID
}

func (r *IDt93) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt93) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt93) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt93) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt93) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt93) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt93) toID() refid.ID {
	return r.ID
}

func (r IDt93) tagVal() byte {
	return tagIDt93
}

type NullIDt93 struct {
	refid.NullID
}

func (u *NullIDt93) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt93) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt93) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt93) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
