// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt155 = 155

type IDt155 struct {
	refid.ID
}

func (r *IDt155) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt155) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt155) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt155) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt155) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt155) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt155) toID() refid.ID {
	return r.ID
}

func (r IDt155) tagVal() byte {
	return tagIDt155
}

type NullIDt155 struct {
	refid.NullID
}

func (u *NullIDt155) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt155) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt155) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt155) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
