// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt132 = 132

type IDt132 struct {
	refid.ID
}

func (r *IDt132) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt132) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt132) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt132) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt132) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt132) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt132) toID() refid.ID {
	return r.ID
}

func (r IDt132) tagVal() byte {
	return tagIDt132
}

type NullIDt132 struct {
	refid.NullID
}

func (u *NullIDt132) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt132) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt132) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt132) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
