// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt71 = 71

type IDt71 struct {
	refid.ID
}

func (r *IDt71) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt71) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt71) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt71) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt71) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt71) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt71) toID() refid.ID {
	return r.ID
}

func (r IDt71) tagVal() byte {
	return tagIDt71
}

type NullIDt71 struct {
	refid.NullID
}

func (u *NullIDt71) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt71) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt71) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt71) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
