// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt94 = 94

type IDt94 struct {
	refid.ID
}

func (r *IDt94) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt94) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt94) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt94) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt94) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt94) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt94) toID() refid.ID {
	return r.ID
}

func (r IDt94) tagVal() byte {
	return tagIDt94
}

type NullIDt94 struct {
	refid.NullID
}

func (u *NullIDt94) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt94) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt94) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt94) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
