// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt96 = 96

type IDt96 struct {
	refid.ID
}

func (r *IDt96) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt96) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt96) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt96) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt96) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt96) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt96) toID() refid.ID {
	return r.ID
}

func (r IDt96) tagVal() byte {
	return tagIDt96
}

type NullIDt96 struct {
	refid.NullID
}

func (u *NullIDt96) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt96) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt96) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt96) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
