// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt81 = 81

type IDt81 struct {
	refid.ID
}

func (r *IDt81) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt81) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt81) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt81) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt81) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt81) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt81) toID() refid.ID {
	return r.ID
}

func (r IDt81) tagVal() byte {
	return tagIDt81
}

type NullIDt81 struct {
	refid.NullID
}

func (u *NullIDt81) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt81) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt81) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt81) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
