// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt162 = 162

type IDt162 struct {
	refid.ID
}

func (r *IDt162) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt162) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt162) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt162) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt162) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt162) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt162) toID() refid.ID {
	return r.ID
}

func (r IDt162) tagVal() byte {
	return tagIDt162
}

type NullIDt162 struct {
	refid.NullID
}

func (u *NullIDt162) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt162) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt162) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt162) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
