// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt28 = 28

type IDt28 struct {
	refid.ID
}

func (r *IDt28) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt28) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt28) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt28) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt28) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt28) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt28) toID() refid.ID {
	return r.ID
}

func (r IDt28) tagVal() byte {
	return tagIDt28
}

type NullIDt28 struct {
	refid.NullID
}

func (u *NullIDt28) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt28) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt28) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt28) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
