// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt47 = 47

type IDt47 struct {
	refid.ID
}

func (r *IDt47) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt47) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt47) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt47) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt47) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt47) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt47) toID() refid.ID {
	return r.ID
}

func (r IDt47) tagVal() byte {
	return tagIDt47
}

type NullIDt47 struct {
	refid.NullID
}

func (u *NullIDt47) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt47) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt47) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt47) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
