// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt216 = 216

type IDt216 struct {
	refid.ID
}

func (r *IDt216) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt216) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt216) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt216) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt216) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt216) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt216) toID() refid.ID {
	return r.ID
}

func (r IDt216) tagVal() byte {
	return tagIDt216
}

type NullIDt216 struct {
	refid.NullID
}

func (u *NullIDt216) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt216) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt216) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt216) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
