// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt91 = 91

type IDt91 struct {
	refid.ID
}

func (r *IDt91) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt91) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt91) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt91) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt91) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt91) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt91) toID() refid.ID {
	return r.ID
}

func (r IDt91) tagVal() byte {
	return tagIDt91
}

type NullIDt91 struct {
	refid.NullID
}

func (u *NullIDt91) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt91) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt91) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt91) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
