// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt214 = 214

type IDt214 struct {
	refid.ID
}

func (r *IDt214) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt214) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt214) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt214) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt214) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt214) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt214) toID() refid.ID {
	return r.ID
}

func (r IDt214) tagVal() byte {
	return tagIDt214
}

type NullIDt214 struct {
	refid.NullID
}

func (u *NullIDt214) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt214) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt214) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt214) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
