// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt244 = 244

type IDt244 struct {
	refid.ID
}

func (r *IDt244) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt244) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt244) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt244) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt244) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt244) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt244) toID() refid.ID {
	return r.ID
}

func (r IDt244) tagVal() byte {
	return tagIDt244
}

type NullIDt244 struct {
	refid.NullID
}

func (u *NullIDt244) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt244) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt244) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt244) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
