// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt197 = 197

type IDt197 struct {
	refid.ID
}

func (r *IDt197) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt197) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt197) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt197) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt197) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt197) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt197) toID() refid.ID {
	return r.ID
}

func (r IDt197) tagVal() byte {
	return tagIDt197
}

type NullIDt197 struct {
	refid.NullID
}

func (u *NullIDt197) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt197) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt197) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt197) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
