// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt67 = 67

type IDt67 struct {
	refid.ID
}

func (r *IDt67) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt67) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt67) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt67) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt67) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt67) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt67) toID() refid.ID {
	return r.ID
}

func (r IDt67) tagVal() byte {
	return tagIDt67
}

type NullIDt67 struct {
	refid.NullID
}

func (u *NullIDt67) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt67) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt67) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt67) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
