// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt102 = 102

type IDt102 struct {
	refid.ID
}

func (r *IDt102) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt102) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt102) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt102) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt102) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt102) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt102) toID() refid.ID {
	return r.ID
}

func (r IDt102) tagVal() byte {
	return tagIDt102
}

type NullIDt102 struct {
	refid.NullID
}

func (u *NullIDt102) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt102) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt102) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt102) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
