// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt104 = 104

type IDt104 struct {
	refid.ID
}

func (r *IDt104) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt104) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt104) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt104) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt104) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt104) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt104) toID() refid.ID {
	return r.ID
}

func (r IDt104) tagVal() byte {
	return tagIDt104
}

type NullIDt104 struct {
	refid.NullID
}

func (u *NullIDt104) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt104) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt104) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt104) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
