// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt5 = 5

type IDt5 struct {
	refid.ID
}

func (r *IDt5) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt5) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt5) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt5) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt5) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt5) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt5) toID() refid.ID {
	return r.ID
}

func (r IDt5) tagVal() byte {
	return tagIDt5
}

type NullIDt5 struct {
	refid.NullID
}

func (u *NullIDt5) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt5) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt5) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt5) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
