// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt248 = 248

type IDt248 struct {
	refid.ID
}

func (r *IDt248) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt248) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt248) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt248) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt248) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt248) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt248) toID() refid.ID {
	return r.ID
}

func (r IDt248) tagVal() byte {
	return tagIDt248
}

type NullIDt248 struct {
	refid.NullID
}

func (u *NullIDt248) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt248) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt248) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt248) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
