// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt100 = 100

type IDt100 struct {
	refid.ID
}

func (r *IDt100) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt100) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt100) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt100) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt100) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt100) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt100) toID() refid.ID {
	return r.ID
}

func (r IDt100) tagVal() byte {
	return tagIDt100
}

type NullIDt100 struct {
	refid.NullID
}

func (u *NullIDt100) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt100) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt100) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt100) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
