// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt37 = 37

type IDt37 struct {
	refid.ID
}

func (r *IDt37) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt37) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt37) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt37) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt37) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt37) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt37) toID() refid.ID {
	return r.ID
}

func (r IDt37) tagVal() byte {
	return tagIDt37
}

type NullIDt37 struct {
	refid.NullID
}

func (u *NullIDt37) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt37) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt37) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt37) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
