// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt232 = 232

type IDt232 struct {
	refid.ID
}

func (r *IDt232) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt232) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt232) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt232) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt232) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt232) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt232) toID() refid.ID {
	return r.ID
}

func (r IDt232) tagVal() byte {
	return tagIDt232
}

type NullIDt232 struct {
	refid.NullID
}

func (u *NullIDt232) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt232) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt232) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt232) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
