// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt209 = 209

type IDt209 struct {
	refid.ID
}

func (r *IDt209) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt209) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt209) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt209) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt209) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt209) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt209) toID() refid.ID {
	return r.ID
}

func (r IDt209) tagVal() byte {
	return tagIDt209
}

type NullIDt209 struct {
	refid.NullID
}

func (u *NullIDt209) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt209) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt209) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt209) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
