// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt241 = 241

type IDt241 struct {
	refid.ID
}

func (r *IDt241) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt241) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt241) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt241) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt241) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt241) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt241) toID() refid.ID {
	return r.ID
}

func (r IDt241) tagVal() byte {
	return tagIDt241
}

type NullIDt241 struct {
	refid.NullID
}

func (u *NullIDt241) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt241) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt241) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt241) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
