// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt116 = 116

type IDt116 struct {
	refid.ID
}

func (r *IDt116) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt116) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt116) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt116) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt116) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt116) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt116) toID() refid.ID {
	return r.ID
}

func (r IDt116) tagVal() byte {
	return tagIDt116
}

type NullIDt116 struct {
	refid.NullID
}

func (u *NullIDt116) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt116) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt116) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt116) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
