// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt1 = 1

type IDt1 struct {
	refid.ID
}

func (r *IDt1) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt1) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt1) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt1) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt1) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt1) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt1) toID() refid.ID {
	return r.ID
}

func (r IDt1) tagVal() byte {
	return tagIDt1
}

type NullIDt1 struct {
	refid.NullID
}

func (u *NullIDt1) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt1) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt1) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt1) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
