// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt80 = 80

type IDt80 struct {
	refid.ID
}

func (r *IDt80) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt80) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt80) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt80) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt80) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt80) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt80) toID() refid.ID {
	return r.ID
}

func (r IDt80) tagVal() byte {
	return tagIDt80
}

type NullIDt80 struct {
	refid.NullID
}

func (u *NullIDt80) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt80) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt80) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt80) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
