// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt111 = 111

type IDt111 struct {
	refid.ID
}

func (r *IDt111) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt111) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt111) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt111) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt111) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt111) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt111) toID() refid.ID {
	return r.ID
}

func (r IDt111) tagVal() byte {
	return tagIDt111
}

type NullIDt111 struct {
	refid.NullID
}

func (u *NullIDt111) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt111) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt111) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt111) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
