// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt68 = 68

type IDt68 struct {
	refid.ID
}

func (r *IDt68) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt68) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt68) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt68) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt68) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt68) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt68) toID() refid.ID {
	return r.ID
}

func (r IDt68) tagVal() byte {
	return tagIDt68
}

type NullIDt68 struct {
	refid.NullID
}

func (u *NullIDt68) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt68) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt68) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt68) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
