// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt129 = 129

type IDt129 struct {
	refid.ID
}

func (r *IDt129) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt129) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt129) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt129) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt129) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt129) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt129) toID() refid.ID {
	return r.ID
}

func (r IDt129) tagVal() byte {
	return tagIDt129
}

type NullIDt129 struct {
	refid.NullID
}

func (u *NullIDt129) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt129) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt129) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt129) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
