// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt250 = 250

type IDt250 struct {
	refid.ID
}

func (r *IDt250) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt250) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt250) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt250) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt250) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt250) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt250) toID() refid.ID {
	return r.ID
}

func (r IDt250) tagVal() byte {
	return tagIDt250
}

type NullIDt250 struct {
	refid.NullID
}

func (u *NullIDt250) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt250) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt250) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt250) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
