// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt238 = 238

type IDt238 struct {
	refid.ID
}

func (r *IDt238) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt238) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt238) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt238) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt238) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt238) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt238) toID() refid.ID {
	return r.ID
}

func (r IDt238) tagVal() byte {
	return tagIDt238
}

type NullIDt238 struct {
	refid.NullID
}

func (u *NullIDt238) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt238) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt238) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt238) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
