// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt242 = 242

type IDt242 struct {
	refid.ID
}

func (r *IDt242) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt242) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt242) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt242) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt242) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt242) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt242) toID() refid.ID {
	return r.ID
}

func (r IDt242) tagVal() byte {
	return tagIDt242
}

type NullIDt242 struct {
	refid.NullID
}

func (u *NullIDt242) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt242) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt242) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt242) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
