// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt127 = 127

type IDt127 struct {
	refid.ID
}

func (r *IDt127) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt127) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt127) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt127) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt127) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt127) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt127) toID() refid.ID {
	return r.ID
}

func (r IDt127) tagVal() byte {
	return tagIDt127
}

type NullIDt127 struct {
	refid.NullID
}

func (u *NullIDt127) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt127) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt127) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt127) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
