// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt181 = 181

type IDt181 struct {
	refid.ID
}

func (r *IDt181) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt181) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt181) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt181) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt181) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt181) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt181) toID() refid.ID {
	return r.ID
}

func (r IDt181) tagVal() byte {
	return tagIDt181
}

type NullIDt181 struct {
	refid.NullID
}

func (u *NullIDt181) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt181) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt181) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt181) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
