// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt43 = 43

type IDt43 struct {
	refid.ID
}

func (r *IDt43) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt43) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt43) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt43) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt43) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt43) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt43) toID() refid.ID {
	return r.ID
}

func (r IDt43) tagVal() byte {
	return tagIDt43
}

type NullIDt43 struct {
	refid.NullID
}

func (u *NullIDt43) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt43) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt43) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt43) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
