// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt38 = 38

type IDt38 struct {
	refid.ID
}

func (r *IDt38) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt38) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt38) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt38) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt38) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt38) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt38) toID() refid.ID {
	return r.ID
}

func (r IDt38) tagVal() byte {
	return tagIDt38
}

type NullIDt38 struct {
	refid.NullID
}

func (u *NullIDt38) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt38) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt38) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt38) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
