// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt174 = 174

type IDt174 struct {
	refid.ID
}

func (r *IDt174) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt174) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt174) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt174) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt174) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt174) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt174) toID() refid.ID {
	return r.ID
}

func (r IDt174) tagVal() byte {
	return tagIDt174
}

type NullIDt174 struct {
	refid.NullID
}

func (u *NullIDt174) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt174) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt174) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt174) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
