// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt172 = 172

type IDt172 struct {
	refid.ID
}

func (r *IDt172) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt172) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt172) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt172) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt172) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt172) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt172) toID() refid.ID {
	return r.ID
}

func (r IDt172) tagVal() byte {
	return tagIDt172
}

type NullIDt172 struct {
	refid.NullID
}

func (u *NullIDt172) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt172) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt172) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt172) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
