// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt247 = 247

type IDt247 struct {
	refid.ID
}

func (r *IDt247) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt247) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt247) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt247) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt247) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt247) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt247) toID() refid.ID {
	return r.ID
}

func (r IDt247) tagVal() byte {
	return tagIDt247
}

type NullIDt247 struct {
	refid.NullID
}

func (u *NullIDt247) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt247) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt247) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt247) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
