// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt52 = 52

type IDt52 struct {
	refid.ID
}

func (r *IDt52) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt52) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt52) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt52) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt52) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt52) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt52) toID() refid.ID {
	return r.ID
}

func (r IDt52) tagVal() byte {
	return tagIDt52
}

type NullIDt52 struct {
	refid.NullID
}

func (u *NullIDt52) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt52) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt52) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt52) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
