// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt60 = 60

type IDt60 struct {
	refid.ID
}

func (r *IDt60) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt60) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt60) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt60) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt60) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt60) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt60) toID() refid.ID {
	return r.ID
}

func (r IDt60) tagVal() byte {
	return tagIDt60
}

type NullIDt60 struct {
	refid.NullID
}

func (u *NullIDt60) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt60) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt60) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt60) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
