// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt140 = 140

type IDt140 struct {
	refid.ID
}

func (r *IDt140) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt140) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt140) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt140) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt140) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt140) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt140) toID() refid.ID {
	return r.ID
}

func (r IDt140) tagVal() byte {
	return tagIDt140
}

type NullIDt140 struct {
	refid.NullID
}

func (u *NullIDt140) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt140) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt140) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt140) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
