// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt254 = 254

type IDt254 struct {
	refid.ID
}

func (r *IDt254) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt254) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt254) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt254) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt254) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt254) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt254) toID() refid.ID {
	return r.ID
}

func (r IDt254) tagVal() byte {
	return tagIDt254
}

type NullIDt254 struct {
	refid.NullID
}

func (u *NullIDt254) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt254) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt254) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt254) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
