// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt41 = 41

type IDt41 struct {
	refid.ID
}

func (r *IDt41) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt41) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt41) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt41) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt41) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt41) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt41) toID() refid.ID {
	return r.ID
}

func (r IDt41) tagVal() byte {
	return tagIDt41
}

type NullIDt41 struct {
	refid.NullID
}

func (u *NullIDt41) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt41) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt41) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt41) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
