// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt142 = 142

type IDt142 struct {
	refid.ID
}

func (r *IDt142) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt142) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt142) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt142) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt142) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt142) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt142) toID() refid.ID {
	return r.ID
}

func (r IDt142) tagVal() byte {
	return tagIDt142
}

type NullIDt142 struct {
	refid.NullID
}

func (u *NullIDt142) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt142) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt142) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt142) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
