// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt8 = 8

type IDt8 struct {
	refid.ID
}

func (r *IDt8) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt8) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt8) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt8) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt8) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt8) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt8) toID() refid.ID {
	return r.ID
}

func (r IDt8) tagVal() byte {
	return tagIDt8
}

type NullIDt8 struct {
	refid.NullID
}

func (u *NullIDt8) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt8) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt8) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt8) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
