// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt234 = 234

type IDt234 struct {
	refid.ID
}

func (r *IDt234) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt234) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt234) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt234) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt234) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt234) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt234) toID() refid.ID {
	return r.ID
}

func (r IDt234) tagVal() byte {
	return tagIDt234
}

type NullIDt234 struct {
	refid.NullID
}

func (u *NullIDt234) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt234) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt234) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt234) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
