// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt65 = 65

type IDt65 struct {
	refid.ID
}

func (r *IDt65) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt65) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt65) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt65) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt65) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt65) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt65) toID() refid.ID {
	return r.ID
}

func (r IDt65) tagVal() byte {
	return tagIDt65
}

type NullIDt65 struct {
	refid.NullID
}

func (u *NullIDt65) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt65) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt65) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt65) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
