// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt133 = 133

type IDt133 struct {
	refid.ID
}

func (r *IDt133) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt133) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt133) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt133) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt133) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt133) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt133) toID() refid.ID {
	return r.ID
}

func (r IDt133) tagVal() byte {
	return tagIDt133
}

type NullIDt133 struct {
	refid.NullID
}

func (u *NullIDt133) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt133) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt133) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt133) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
