// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt30 = 30

type IDt30 struct {
	refid.ID
}

func (r *IDt30) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt30) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt30) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt30) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt30) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt30) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt30) toID() refid.ID {
	return r.ID
}

func (r IDt30) tagVal() byte {
	return tagIDt30
}

type NullIDt30 struct {
	refid.NullID
}

func (u *NullIDt30) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt30) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt30) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt30) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
