// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt208 = 208

type IDt208 struct {
	refid.ID
}

func (r *IDt208) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt208) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt208) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt208) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt208) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt208) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt208) toID() refid.ID {
	return r.ID
}

func (r IDt208) tagVal() byte {
	return tagIDt208
}

type NullIDt208 struct {
	refid.NullID
}

func (u *NullIDt208) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt208) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt208) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt208) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
