// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt176 = 176

type IDt176 struct {
	refid.ID
}

func (r *IDt176) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt176) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt176) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt176) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt176) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt176) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt176) toID() refid.ID {
	return r.ID
}

func (r IDt176) tagVal() byte {
	return tagIDt176
}

type NullIDt176 struct {
	refid.NullID
}

func (u *NullIDt176) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt176) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt176) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt176) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
