// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt53 = 53

type IDt53 struct {
	refid.ID
}

func (r *IDt53) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt53) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt53) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt53) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt53) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt53) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt53) toID() refid.ID {
	return r.ID
}

func (r IDt53) tagVal() byte {
	return tagIDt53
}

type NullIDt53 struct {
	refid.NullID
}

func (u *NullIDt53) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt53) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt53) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt53) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
