// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt128 = 128

type IDt128 struct {
	refid.ID
}

func (r *IDt128) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt128) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt128) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt128) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt128) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt128) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt128) toID() refid.ID {
	return r.ID
}

func (r IDt128) tagVal() byte {
	return tagIDt128
}

type NullIDt128 struct {
	refid.NullID
}

func (u *NullIDt128) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt128) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt128) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt128) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
