// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt159 = 159

type IDt159 struct {
	refid.ID
}

func (r *IDt159) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt159) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt159) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt159) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt159) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt159) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt159) toID() refid.ID {
	return r.ID
}

func (r IDt159) tagVal() byte {
	return tagIDt159
}

type NullIDt159 struct {
	refid.NullID
}

func (u *NullIDt159) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt159) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt159) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt159) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
