// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt34 = 34

type IDt34 struct {
	refid.ID
}

func (r *IDt34) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt34) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt34) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt34) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt34) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt34) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt34) toID() refid.ID {
	return r.ID
}

func (r IDt34) tagVal() byte {
	return tagIDt34
}

type NullIDt34 struct {
	refid.NullID
}

func (u *NullIDt34) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt34) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt34) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt34) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
