// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt223 = 223

type IDt223 struct {
	refid.ID
}

func (r *IDt223) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt223) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt223) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt223) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt223) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt223) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt223) toID() refid.ID {
	return r.ID
}

func (r IDt223) tagVal() byte {
	return tagIDt223
}

type NullIDt223 struct {
	refid.NullID
}

func (u *NullIDt223) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt223) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt223) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt223) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
