// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt170 = 170

type IDt170 struct {
	refid.ID
}

func (r *IDt170) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt170) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt170) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt170) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt170) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt170) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt170) toID() refid.ID {
	return r.ID
}

func (r IDt170) tagVal() byte {
	return tagIDt170
}

type NullIDt170 struct {
	refid.NullID
}

func (u *NullIDt170) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt170) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt170) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt170) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
