// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt17 = 17

type IDt17 struct {
	refid.ID
}

func (r *IDt17) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt17) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt17) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt17) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt17) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt17) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt17) toID() refid.ID {
	return r.ID
}

func (r IDt17) tagVal() byte {
	return tagIDt17
}

type NullIDt17 struct {
	refid.NullID
}

func (u *NullIDt17) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt17) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt17) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt17) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
