// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt177 = 177

type IDt177 struct {
	refid.ID
}

func (r *IDt177) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt177) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt177) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt177) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt177) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt177) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt177) toID() refid.ID {
	return r.ID
}

func (r IDt177) tagVal() byte {
	return tagIDt177
}

type NullIDt177 struct {
	refid.NullID
}

func (u *NullIDt177) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt177) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt177) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt177) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
