// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt36 = 36

type IDt36 struct {
	refid.ID
}

func (r *IDt36) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt36) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt36) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt36) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt36) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt36) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt36) toID() refid.ID {
	return r.ID
}

func (r IDt36) tagVal() byte {
	return tagIDt36
}

type NullIDt36 struct {
	refid.NullID
}

func (u *NullIDt36) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt36) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt36) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt36) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
