// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt64 = 64

type IDt64 struct {
	refid.ID
}

func (r *IDt64) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt64) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt64) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt64) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt64) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt64) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt64) toID() refid.ID {
	return r.ID
}

func (r IDt64) tagVal() byte {
	return tagIDt64
}

type NullIDt64 struct {
	refid.NullID
}

func (u *NullIDt64) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt64) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt64) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt64) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
