// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt188 = 188

type IDt188 struct {
	refid.ID
}

func (r *IDt188) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt188) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt188) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt188) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt188) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt188) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt188) toID() refid.ID {
	return r.ID
}

func (r IDt188) tagVal() byte {
	return tagIDt188
}

type NullIDt188 struct {
	refid.NullID
}

func (u *NullIDt188) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt188) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt188) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt188) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
