// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt204 = 204

type IDt204 struct {
	refid.ID
}

func (r *IDt204) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt204) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt204) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt204) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt204) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt204) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt204) toID() refid.ID {
	return r.ID
}

func (r IDt204) tagVal() byte {
	return tagIDt204
}

type NullIDt204 struct {
	refid.NullID
}

func (u *NullIDt204) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt204) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt204) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt204) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
