// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt108 = 108

type IDt108 struct {
	refid.ID
}

func (r *IDt108) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt108) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt108) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt108) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt108) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt108) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt108) toID() refid.ID {
	return r.ID
}

func (r IDt108) tagVal() byte {
	return tagIDt108
}

type NullIDt108 struct {
	refid.NullID
}

func (u *NullIDt108) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt108) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt108) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt108) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
