// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt87 = 87

type IDt87 struct {
	refid.ID
}

func (r *IDt87) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt87) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt87) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt87) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt87) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt87) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt87) toID() refid.ID {
	return r.ID
}

func (r IDt87) tagVal() byte {
	return tagIDt87
}

type NullIDt87 struct {
	refid.NullID
}

func (u *NullIDt87) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt87) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt87) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt87) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
