// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt211 = 211

type IDt211 struct {
	refid.ID
}

func (r *IDt211) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt211) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt211) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt211) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt211) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt211) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt211) toID() refid.ID {
	return r.ID
}

func (r IDt211) tagVal() byte {
	return tagIDt211
}

type NullIDt211 struct {
	refid.NullID
}

func (u *NullIDt211) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt211) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt211) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt211) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
