// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt144 = 144

type IDt144 struct {
	refid.ID
}

func (r *IDt144) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt144) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt144) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt144) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt144) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt144) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt144) toID() refid.ID {
	return r.ID
}

func (r IDt144) tagVal() byte {
	return tagIDt144
}

type NullIDt144 struct {
	refid.NullID
}

func (u *NullIDt144) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt144) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt144) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt144) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
