// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt50 = 50

type IDt50 struct {
	refid.ID
}

func (r *IDt50) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt50) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt50) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt50) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt50) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt50) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt50) toID() refid.ID {
	return r.ID
}

func (r IDt50) tagVal() byte {
	return tagIDt50
}

type NullIDt50 struct {
	refid.NullID
}

func (u *NullIDt50) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt50) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt50) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt50) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
