// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt201 = 201

type IDt201 struct {
	refid.ID
}

func (r *IDt201) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt201) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt201) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt201) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt201) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt201) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt201) toID() refid.ID {
	return r.ID
}

func (r IDt201) tagVal() byte {
	return tagIDt201
}

type NullIDt201 struct {
	refid.NullID
}

func (u *NullIDt201) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt201) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt201) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt201) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
