// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt240 = 240

type IDt240 struct {
	refid.ID
}

func (r *IDt240) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt240) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt240) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt240) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt240) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt240) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt240) toID() refid.ID {
	return r.ID
}

func (r IDt240) tagVal() byte {
	return tagIDt240
}

type NullIDt240 struct {
	refid.NullID
}

func (u *NullIDt240) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt240) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt240) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt240) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
