// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt237 = 237

type IDt237 struct {
	refid.ID
}

func (r *IDt237) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt237) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt237) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt237) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt237) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt237) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt237) toID() refid.ID {
	return r.ID
}

func (r IDt237) tagVal() byte {
	return tagIDt237
}

type NullIDt237 struct {
	refid.NullID
}

func (u *NullIDt237) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt237) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt237) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt237) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
