// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt78 = 78

type IDt78 struct {
	refid.ID
}

func (r *IDt78) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt78) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt78) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt78) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt78) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt78) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt78) toID() refid.ID {
	return r.ID
}

func (r IDt78) tagVal() byte {
	return tagIDt78
}

type NullIDt78 struct {
	refid.NullID
}

func (u *NullIDt78) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt78) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt78) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt78) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
