// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt157 = 157

type IDt157 struct {
	refid.ID
}

func (r *IDt157) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt157) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt157) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt157) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt157) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt157) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt157) toID() refid.ID {
	return r.ID
}

func (r IDt157) tagVal() byte {
	return tagIDt157
}

type NullIDt157 struct {
	refid.NullID
}

func (u *NullIDt157) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt157) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt157) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt157) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
