// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt153 = 153

type IDt153 struct {
	refid.ID
}

func (r *IDt153) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt153) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt153) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt153) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt153) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt153) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt153) toID() refid.ID {
	return r.ID
}

func (r IDt153) tagVal() byte {
	return tagIDt153
}

type NullIDt153 struct {
	refid.NullID
}

func (u *NullIDt153) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt153) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt153) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt153) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
