// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt12 = 12

type IDt12 struct {
	refid.ID
}

func (r *IDt12) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt12) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt12) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt12) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt12) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt12) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt12) toID() refid.ID {
	return r.ID
}

func (r IDt12) tagVal() byte {
	return tagIDt12
}

type NullIDt12 struct {
	refid.NullID
}

func (u *NullIDt12) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt12) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt12) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt12) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
