// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt106 = 106

type IDt106 struct {
	refid.ID
}

func (r *IDt106) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt106) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt106) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt106) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt106) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt106) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt106) toID() refid.ID {
	return r.ID
}

func (r IDt106) tagVal() byte {
	return tagIDt106
}

type NullIDt106 struct {
	refid.NullID
}

func (u *NullIDt106) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt106) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt106) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt106) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
