// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt49 = 49

type IDt49 struct {
	refid.ID
}

func (r *IDt49) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt49) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt49) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt49) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt49) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt49) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt49) toID() refid.ID {
	return r.ID
}

func (r IDt49) tagVal() byte {
	return tagIDt49
}

type NullIDt49 struct {
	refid.NullID
}

func (u *NullIDt49) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt49) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt49) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt49) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
