// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt198 = 198

type IDt198 struct {
	refid.ID
}

func (r *IDt198) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt198) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt198) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt198) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt198) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt198) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt198) toID() refid.ID {
	return r.ID
}

func (r IDt198) tagVal() byte {
	return tagIDt198
}

type NullIDt198 struct {
	refid.NullID
}

func (u *NullIDt198) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt198) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt198) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt198) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
