// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt154 = 154

type IDt154 struct {
	refid.ID
}

func (r *IDt154) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt154) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt154) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt154) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt154) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt154) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt154) toID() refid.ID {
	return r.ID
}

func (r IDt154) tagVal() byte {
	return tagIDt154
}

type NullIDt154 struct {
	refid.NullID
}

func (u *NullIDt154) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt154) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt154) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt154) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
