// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt24 = 24

type IDt24 struct {
	refid.ID
}

func (r *IDt24) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt24) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt24) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt24) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt24) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt24) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt24) toID() refid.ID {
	return r.ID
}

func (r IDt24) tagVal() byte {
	return tagIDt24
}

type NullIDt24 struct {
	refid.NullID
}

func (u *NullIDt24) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt24) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt24) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt24) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
