// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt221 = 221

type IDt221 struct {
	refid.ID
}

func (r *IDt221) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt221) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt221) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt221) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt221) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt221) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt221) toID() refid.ID {
	return r.ID
}

func (r IDt221) tagVal() byte {
	return tagIDt221
}

type NullIDt221 struct {
	refid.NullID
}

func (u *NullIDt221) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt221) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt221) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt221) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
