// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt51 = 51

type IDt51 struct {
	refid.ID
}

func (r *IDt51) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt51) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt51) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt51) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt51) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt51) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt51) toID() refid.ID {
	return r.ID
}

func (r IDt51) tagVal() byte {
	return tagIDt51
}

type NullIDt51 struct {
	refid.NullID
}

func (u *NullIDt51) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt51) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt51) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt51) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
