// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt202 = 202

type IDt202 struct {
	refid.ID
}

func (r *IDt202) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt202) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt202) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt202) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt202) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt202) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt202) toID() refid.ID {
	return r.ID
}

func (r IDt202) tagVal() byte {
	return tagIDt202
}

type NullIDt202 struct {
	refid.NullID
}

func (u *NullIDt202) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt202) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt202) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt202) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
