// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt235 = 235

type IDt235 struct {
	refid.ID
}

func (r *IDt235) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt235) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt235) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt235) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt235) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt235) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt235) toID() refid.ID {
	return r.ID
}

func (r IDt235) tagVal() byte {
	return tagIDt235
}

type NullIDt235 struct {
	refid.NullID
}

func (u *NullIDt235) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt235) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt235) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt235) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
