// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt173 = 173

type IDt173 struct {
	refid.ID
}

func (r *IDt173) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt173) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt173) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt173) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt173) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt173) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt173) toID() refid.ID {
	return r.ID
}

func (r IDt173) tagVal() byte {
	return tagIDt173
}

type NullIDt173 struct {
	refid.NullID
}

func (u *NullIDt173) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt173) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt173) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt173) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
