// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt213 = 213

type IDt213 struct {
	refid.ID
}

func (r *IDt213) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt213) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt213) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt213) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt213) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt213) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt213) toID() refid.ID {
	return r.ID
}

func (r IDt213) tagVal() byte {
	return tagIDt213
}

type NullIDt213 struct {
	refid.NullID
}

func (u *NullIDt213) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt213) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt213) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt213) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
