// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt90 = 90

type IDt90 struct {
	refid.ID
}

func (r *IDt90) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt90) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt90) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt90) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt90) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt90) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt90) toID() refid.ID {
	return r.ID
}

func (r IDt90) tagVal() byte {
	return tagIDt90
}

type NullIDt90 struct {
	refid.NullID
}

func (u *NullIDt90) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt90) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt90) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt90) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
