// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt251 = 251

type IDt251 struct {
	refid.ID
}

func (r *IDt251) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt251) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt251) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt251) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt251) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt251) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt251) toID() refid.ID {
	return r.ID
}

func (r IDt251) tagVal() byte {
	return tagIDt251
}

type NullIDt251 struct {
	refid.NullID
}

func (u *NullIDt251) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt251) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt251) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt251) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
