// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt167 = 167

type IDt167 struct {
	refid.ID
}

func (r *IDt167) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt167) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt167) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt167) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt167) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt167) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt167) toID() refid.ID {
	return r.ID
}

func (r IDt167) tagVal() byte {
	return tagIDt167
}

type NullIDt167 struct {
	refid.NullID
}

func (u *NullIDt167) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt167) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt167) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt167) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
