// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt32 = 32

type IDt32 struct {
	refid.ID
}

func (r *IDt32) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt32) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt32) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt32) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt32) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt32) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt32) toID() refid.ID {
	return r.ID
}

func (r IDt32) tagVal() byte {
	return tagIDt32
}

type NullIDt32 struct {
	refid.NullID
}

func (u *NullIDt32) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt32) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt32) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt32) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
