// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt103 = 103

type IDt103 struct {
	refid.ID
}

func (r *IDt103) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt103) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt103) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt103) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt103) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt103) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt103) toID() refid.ID {
	return r.ID
}

func (r IDt103) tagVal() byte {
	return tagIDt103
}

type NullIDt103 struct {
	refid.NullID
}

func (u *NullIDt103) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt103) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt103) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt103) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
