// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt122 = 122

type IDt122 struct {
	refid.ID
}

func (r *IDt122) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt122) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt122) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt122) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt122) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt122) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt122) toID() refid.ID {
	return r.ID
}

func (r IDt122) tagVal() byte {
	return tagIDt122
}

type NullIDt122 struct {
	refid.NullID
}

func (u *NullIDt122) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt122) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt122) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt122) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
