// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt236 = 236

type IDt236 struct {
	refid.ID
}

func (r *IDt236) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt236) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt236) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt236) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt236) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt236) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt236) toID() refid.ID {
	return r.ID
}

func (r IDt236) tagVal() byte {
	return tagIDt236
}

type NullIDt236 struct {
	refid.NullID
}

func (u *NullIDt236) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt236) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt236) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt236) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
