// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt179 = 179

type IDt179 struct {
	refid.ID
}

func (r *IDt179) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt179) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt179) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt179) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt179) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt179) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt179) toID() refid.ID {
	return r.ID
}

func (r IDt179) tagVal() byte {
	return tagIDt179
}

type NullIDt179 struct {
	refid.NullID
}

func (u *NullIDt179) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt179) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt179) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt179) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
