// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt83 = 83

type IDt83 struct {
	refid.ID
}

func (r *IDt83) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt83) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt83) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt83) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt83) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt83) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt83) toID() refid.ID {
	return r.ID
}

func (r IDt83) tagVal() byte {
	return tagIDt83
}

type NullIDt83 struct {
	refid.NullID
}

func (u *NullIDt83) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt83) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt83) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt83) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
