// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt46 = 46

type IDt46 struct {
	refid.ID
}

func (r *IDt46) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt46) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt46) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt46) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt46) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt46) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt46) toID() refid.ID {
	return r.ID
}

func (r IDt46) tagVal() byte {
	return tagIDt46
}

type NullIDt46 struct {
	refid.NullID
}

func (u *NullIDt46) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt46) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt46) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt46) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
