// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt151 = 151

type IDt151 struct {
	refid.ID
}

func (r *IDt151) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt151) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt151) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt151) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt151) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt151) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt151) toID() refid.ID {
	return r.ID
}

func (r IDt151) tagVal() byte {
	return tagIDt151
}

type NullIDt151 struct {
	refid.NullID
}

func (u *NullIDt151) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt151) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt151) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt151) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
