// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagIDt10 = 10

type IDt10 struct {
	refid.ID
}

func (r *IDt10) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt10) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt10) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt10) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt10) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt10) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt10) toID() refid.ID {
	return r.ID
}

func (r IDt10) tagVal() byte {
	return tagIDt10
}

type NullIDt10 struct {
	refid.NullID
}

func (u *NullIDt10) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt10) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt10) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt10) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
