// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt2 = 2

type IDt2 struct {
	refid.ID
}

func (r *IDt2) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt2) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt2) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt2) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt2) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt2) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt2) toID() refid.ID {
	return r.ID
}

func (r IDt2) tagVal() byte {
	return tagIDt2
}

type NullIDt2 struct {
	refid.NullID
}

func (u *NullIDt2) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt2) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt2) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt2) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
