// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt21 = 21

type IDt21 struct {
	refid.ID
}

func (r *IDt21) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt21) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt21) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt21) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt21) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt21) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt21) toID() refid.ID {
	return r.ID
}

func (r IDt21) tagVal() byte {
	return tagIDt21
}

type NullIDt21 struct {
	refid.NullID
}

func (u *NullIDt21) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt21) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt21) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt21) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
