// Code generated by refidgen. DO NOT EDIT.
// generated from: reftag.go

package reftag

import (
	"fmt"

	"github.com/dropwhile/refid/v2"
)

const tagIDt195 = 195

type IDt195 struct {
	refid.ID
}

func (r *IDt195) Validate(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagIDt195) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *IDt195) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.Validate(err)
}

func (r *IDt195) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.Validate(err)
}

func (r *IDt195) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.Validate(err)
}

func (r *IDt195) UnmarshalText(b []byte) error {
	err := r.ID.UnmarshalText(b)
	return r.Validate(err)
}

func (r IDt195) toID() refid.ID {
	return r.ID
}

func (r IDt195) tagVal() byte {
	return tagIDt195
}

type NullIDt195 struct {
	refid.NullID
}

func (u *NullIDt195) Validate(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagIDt195) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (u *NullIDt195) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.Validate(err)
}

func (u *NullIDt195) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.Validate(err)
}
