name: unit-tests
on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Src Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          check-latest: true
        id: go

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
          CI: true
        run: make build

      - name: Check
        env:
          GOPROXY: "https://proxy.golang.org"
          CI: true
        run: |
          make check

      - name: Tests
        env:
          GOPROXY: "https://proxy.golang.org"
          CI: true
        run: make test
